CREATE TABLE CLIENT(
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(100) NOT NULL
);

CREATE TABLE PRODUCT(
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  DESCRIPTION VARCHAR(100) NOT NULL,
  PRICE_UNITARY NUMERIC(20, 2)
);

CREATE TABLE ORDER_CLIENT(
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  CLIENT_ID INTEGER REFERENCES CLIENT (ID),
  DATA_ORDER  TIMESTAMP,
  TOTAL NUMERIC(20, 2)
);

CREATE TABLE ITEM_ORDER(
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  ORDER_ID INTEGER REFERENCES ORDER_CLIENT (ID),
  PRODUCT_ID INTEGER REFERENCES PRODUCT (ID),
  AMOUNT INTEGER
);